services:
  service-discovery-eureka:
    build: .
    container_name: service-discovery-eureka
    ports:
      - "8761:8761"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://service-discovery-eureka:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

    networks:
      - cdd-network

networks:
  cdd-network:
    external: true